version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: front_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend/backend
    container_name: back_container
    ports:
      - '8000:8000'
    volumes:
      - ./backend/backend:/app
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'

  celery:
    build: ./backend/backend
    container_name: celery_container
    command: celery -A backend worker -l info
    volumes:
      - ./backend/backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DEBUG=1
