version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: front_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend/backend
    container_name: back_container
    ports:
      - '8000:8000'
    volumes:
      - ./backend/backend:/app
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: ./backend/backend
    container_name: celery_worker
    command: celery -A backend worker -l info
    volumes:
      - ./backend/backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
