version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  backend:
    build: ./backend/backend
    container_name: backend_container
    ports:
      - '8000:8000'
    volumes:
      - ./backend/backend:/app